/**
 * Scaffold the plan lifecycle into a repository, identically everywhere.
 *
 * The rules live in three places: each harness's global rules and Stop hook, the global
 * plan skills, and a committed README in every repo — the copy a tool reads when it has
 * neither of the others. This produces that README and the lifecycle folders.
 *
 * Belongs to the plan-lifecycle skill; the template it renders sits beside it. Run from the
 * repo root:
 *
 *   node ~/.kimi-code/skills/plan-lifecycle/scripts/init-plans.js          # create what is missing
 *   node ~/.kimi-code/skills/plan-lifecycle/scripts/init-plans.js --dry    # show what it would do
 *   node ~/.kimi-code/skills/plan-lifecycle/scripts/init-plans.js --force  # also rewrite the README
 *
 * Idempotent: safe to re-run. It creates the three folders, renders docs/plans/README.md from
 * the global template, and adds a pointer row to whichever agent entry files the repo has. It
 * never deletes or moves a plan, and never vendors a skill — a project copy of a global skill
 * shadows the global one in every harness.
 *
 * Rendering is per repo, so --force is safe: the STATUS.md paragraph names the repo's own
 * scripts/plan-status.{js,mjs} or is dropped when there is none, and folder-table rows the
 * repo added (asset directories) are carried over.
 *
 * SEARCH TAGS: plan scaffold, docs/plans, lifecycle folders, init plans, cross-tool rules
 */

const fs = require("fs");
const path = require("path");

// Resolved from this file, not from HOME: the template ships with the skill, so a relocated
// copy of the skill still finds its own template rather than a stale global one.
const TEMPLATE = path.join(__dirname, "..", "templates", "plans-README.md");

const PLANS_DIR = "docs/plans";
const LIFECYCLE = ["WIP", "completed"];
// Entry files an agent reads first. Each carries a routing table; the pointer goes there.
const ENTRY_FILES = ["CLAUDE.md", "AGENTS.md"];
const TABLE_HEADER = /^\|\s*Need\s*\|\s*File\s*\|/i;
const POINTER =
  "| Plan lifecycle folders, ledger, status enums — binding when executing any plan | `docs/plans/README.md` |";
const POINTER_MARK = "docs/plans/README.md";
// The template's STATUS.md paragraph as written there; render() adapts or drops it. Matched
// to the first blank line, not to a fixed line count — the paragraph has been rewritten
// twice, and a two-line pattern silently stopped matching the moment it grew.
const STATUS_SCRIPT = "`scripts/plan-status.js`";
const STATUS_PARAGRAPH =
  /^`docs\/plans\/STATUS\.md` is generated by `scripts\/plan-status\.js`[\s\S]*?\n\n/m;
const FOLDER_HEADER = /^\|\s*Folder\s*\|/;

const args = process.argv.slice(2);
const dryRun = args.includes("--dry");
const force = args.includes("--force");

const did = [];
const skipped = [];
const manual = [];

function ensureDir(rel) {
  const abs = path.join(process.cwd(), rel);
  if (fs.existsSync(abs)) {
    skipped.push(`${rel}/ already exists`);
    return;
  }
  did.push(`create ${rel}/`);
  if (!dryRun) fs.mkdirSync(abs, { recursive: true });
}

/** Git does not track empty directories, so an empty lifecycle folder needs a keep file. */
function ensureKeep(rel) {
  const dir = path.join(process.cwd(), rel);
  let entries = [];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    /* created above in a real run; in --dry it may not exist yet */
  }
  if (entries.some((e) => e !== ".gitkeep")) return; // has real content, keep file unneeded
  if (entries.includes(".gitkeep")) return;
  did.push(`create ${rel}/.gitkeep`);
  if (!dryRun) fs.writeFileSync(path.join(dir, ".gitkeep"), "");
}

/** Lines of text plus the [start, end) span of the first `| Folder |` table's body rows. */
function folderTable(text) {
  const lines = text.split("\n");
  const header = lines.findIndex((l) => FOLDER_HEADER.test(l));
  if (header === -1) return { lines, start: -1, end: -1 };
  let end = header + 2; // skip the header and separator rows
  while (end < lines.length && lines[end].trim().startsWith("|")) end++;
  return { lines, start: header + 2, end };
}

const firstCell = (row) => row.split("|")[1].trim();

/** The template adapted to this repo: its status script, and the folder rows it added. */
function render(template, current) {
  let text = template;
  const has = (f) => fs.existsSync(path.join(process.cwd(), "scripts", f));
  if (!has("plan-status.js")) {
    if (has("plan-status.mjs")) {
      text = text.split(STATUS_SCRIPT).join("`scripts/plan-status.mjs`");
    } else {
      const dropped = text.replace(STATUS_PARAGRAPH, "");
      if (dropped === text) manual.push("template STATUS.md paragraph not found — check it by hand");
      text = dropped;
    }
  }
  if (current) {
    const cur = folderTable(current);
    const tpl = folderTable(text);
    if (cur.start !== -1 && tpl.start !== -1) {
      const known = new Set(tpl.lines.slice(tpl.start, tpl.end).map(firstCell));
      const added = cur.lines.slice(cur.start, cur.end).filter((row) => !known.has(firstCell(row)));
      if (added.length) {
        tpl.lines.splice(tpl.end, 0, ...added);
        text = tpl.lines.join("\n");
      }
    }
  }
  return text;
}

function writeReadme() {
  const rel = `${PLANS_DIR}/README.md`;
  const abs = path.join(process.cwd(), rel);
  let template;
  try {
    template = fs.readFileSync(TEMPLATE, "utf8");
  } catch {
    manual.push(`template missing at ${TEMPLATE} — cannot write ${rel}`);
    return;
  }
  const current = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
  const next = render(template, current);
  if (current !== null) {
    if (current === next) {
      skipped.push(`${rel} already matches the template`);
      return;
    }
    if (!force) {
      manual.push(`${rel} differs from the template — re-run with --force (repo-added folder rows are kept)`);
      return;
    }
  }
  did.push(`write ${rel}`);
  if (!dryRun) fs.writeFileSync(abs, next);
}

/** Add the pointer row to a routing table, or report that it needs placing by hand. */
function addPointer(rel) {
  const abs = path.join(process.cwd(), rel);
  let text;
  try {
    text = fs.readFileSync(abs, "utf8");
  } catch {
    return; // repo does not use this entry file
  }
  if (text.includes(POINTER_MARK)) {
    skipped.push(`${rel} already points at the plans README`);
    return;
  }

  const lines = text.split("\n");
  const header = lines.findIndex((l) => TABLE_HEADER.test(l));
  if (header === -1) {
    manual.push(`${rel} has no "| Need | File |" table — add this line yourself:\n      ${POINTER}`);
    return;
  }
  // Insert after the last consecutive table row, so the pointer joins the existing table.
  let end = header + 1;
  while (end < lines.length && lines[end].trim().startsWith("|")) end++;
  lines.splice(end, 0, POINTER);

  did.push(`add pointer row to ${rel}`);
  if (!dryRun) fs.writeFileSync(abs, lines.join("\n"));
}

ensureDir(PLANS_DIR);
for (const sub of LIFECYCLE) ensureDir(`${PLANS_DIR}/${sub}`);
if (!dryRun) for (const sub of LIFECYCLE) ensureKeep(`${PLANS_DIR}/${sub}`);
writeReadme();
for (const rel of ENTRY_FILES) addPointer(rel);

for (const line of skipped) console.log(`skip   ${line}`);
for (const line of manual) console.log(`MANUAL ${line}`);
for (const line of did) console.log(`${dryRun ? "would " : ""}do     ${line}`);
console.log(
  `\n${did.length} action(s) ${dryRun ? "planned" : "applied"}` +
    (manual.length ? `, ${manual.length} needing a decision` : "")
);
